# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20170120_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountproblemvisited',
            old_name='submissions',
            new_name='submission',
        ),
        migrations.AlterField(
            model_name='problemsetitem',
            name='permission',
            field=models.SmallIntegerField(default=3),
        ),
    ]
