# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20170228_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemclassify',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='problemclassify',
            name='problemset',
        ),
        migrations.RemoveField(
            model_name='problemsetitem',
            name='classifications',
        ),
        migrations.DeleteModel(
            name='ProblemClassify',
        ),
    ]
