# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_auto_20170314_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemsetitem',
            name='permission',
        ),
        migrations.AddField(
            model_name='problem',
            name='permission',
            field=models.SmallIntegerField(default=3),
        ),
    ]
