# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_auto_20170323_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgestatus',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
