# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_auto_20170402_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgestatus',
            name='virtual_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.ProblemSetItem'),
        ),
    ]
