# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0012_judgestatus_virtual_problem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountproblemvisited',
            options={'verbose_name': '题目-用户访问', 'verbose_name_plural': '题目-用户访问'},
        ),
        migrations.AlterModelOptions(
            name='judgestatus',
            options={'verbose_name': '评测状态', 'verbose_name_plural': '评测状态'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': '题目-信息表', 'verbose_name_plural': '题目-信息表'},
        ),
        migrations.AlterModelOptions(
            name='problemset',
            options={'verbose_name': '题目集', 'verbose_name_plural': '题目集'},
        ),
        migrations.AlterModelOptions(
            name='problemsetitem',
            options={'verbose_name': '题目集-题目项', 'verbose_name_plural': '题目集-题目项'},
        ),
        migrations.AlterModelOptions(
            name='tdgeneratorstatus',
            options={'verbose_name': '题目-测试数据生成队列', 'verbose_name_plural': '题目-测试数据生成队列'},
        ),
    ]
