# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0013_auto_20170403_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsetitem',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
