# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_problemsetitem_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountproblemvisited',
            options={'verbose_name': '账户题目访问计数器缓存', 'verbose_name_plural': '账户题目访问计数器缓存'},
        ),
        migrations.AddField(
            model_name='accountproblemvisited',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
