# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wejudge.db.converter


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_auto_20170518_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.ProblemClassify')),
                ('problemset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.ProblemSet')),
            ],
            options={
                'verbose_name_plural': '题目分类',
                'verbose_name': '题目分类',
            },
            bases=(models.Model, wejudge.db.converter.ModelConverter),
        ),
        migrations.AddField(
            model_name='problemsetitem',
            name='classifications',
            field=models.ManyToManyField(blank=True, to='problem.ProblemClassify'),
        ),
    ]
