# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_auto_20170704_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
