# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0017_problemset_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='publish_private',
            field=models.BooleanField(default=True),
        ),
    ]
