# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0018_problemset_publish_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='items_count',
            field=models.IntegerField(default=0),
        ),
    ]
