# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0019_problemset_items_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='permission',
            field=models.SmallIntegerField(default=7),
        ),
    ]
