# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0020_auto_20170718_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsetitem',
            name='problemset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_of_problemset', to='problem.ProblemSet'),
        ),
    ]
