# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0021_problemsetitem_problemset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemsetitem',
            name='classifications',
        ),
        migrations.AddField(
            model_name='problemsetitem',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.ProblemClassify'),
        ),
    ]
