# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0022_auto_20170726_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='single_testcase',
            field=models.BooleanField(default=False),
        ),
    ]
