# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0026_tdgeneratorstatus_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TDGeneratorStatus',
            new_name='TCGeneratorStatus',
        ),
    ]
