# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0027_auto_20170818_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcgeneratorstatus',
            name='code_len',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tcgeneratorstatus',
            name='code_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tcgeneratorstatus',
            name='flag',
            field=models.SmallIntegerField(default=-2),
        ),
    ]
