# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20170905_0032'),
        ('problem', '0031_auto_20170920_1616'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problemsetsolution',
            unique_together=set([('problemset', 'problem', 'virtual_problem', 'author')]),
        ),
    ]
