# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0032_auto_20171005_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='private',
            field=models.IntegerField(default=0),
        ),
    ]
