# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '比赛题目-公告',
                'verbose_name_plural': '比赛题目-公告',
            },
        ),
        migrations.RemoveField(
            model_name='contest',
            name='rank_list',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='rank_list_cache_before_stop',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='rank_list_cache_time',
        ),
        migrations.AddField(
            model_name='contestaccount',
            name='finally_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestaccount',
            name='ignore_rank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestaccount',
            name='rank_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestaccount',
            name='rank_timeused',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contestsolution',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestsolution',
            name='is_first_blood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestsolution',
            name='used_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='notice',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.ContestAccount'),
        ),
        migrations.AddField(
            model_name='notice',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
        ),
    ]
