# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20170407_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='rank_submission',
            field=models.IntegerField(default=0),
        ),
    ]
