# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-09 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_contest_rank_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsolution',
            name='used_time_real',
            field=models.FloatField(default=0),
        ),
    ]
