# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_contestsolution_used_time_real'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='rank_submission',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_content',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_referee',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_time',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='parent',
        ),
        migrations.AddField(
            model_name='faq',
            name='childrens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.FAQ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_root',
            field=models.BooleanField(default=True),
        ),
    ]
