# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20170411_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='childrens',
        ),
        migrations.AddField(
            model_name='faq',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.FAQ'),
        ),
    ]
