# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-13 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20170411_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestaccount',
            name='clear_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
