# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wejudge.db.converter


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_contestaccount_clear_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestCodeCrossCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levenshtein_similarity_ratio', models.FloatField(default=0)),
                ('contest', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('problem', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contest.ContestProblem')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_status', to='contest.JudgeStatus')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_status2', to='contest.JudgeStatus')),
            ],
            options={
                'verbose_name_plural': '比赛-简单代码查重',
                'verbose_name': '比赛-简单代码查重',
            },
            bases=(models.Model, wejudge.db.converter.ModelConverter),
        ),
        migrations.RemoveField(
            model_name='contestcodeanalysis',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contestcodeanalysis',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='contestcodeanalysis',
            name='status1',
        ),
        migrations.RemoveField(
            model_name='contestcodeanalysis',
            name='status2',
        ),
        migrations.DeleteModel(
            name='ContestCodeAnalysis',
        ),
    ]
