# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20170415_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestaccount',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
