# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20170419_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='cross_check_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='cross_check_public_ratio',
            field=models.FloatField(default=0.8),
        ),
    ]
