# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20170424_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestcodecrosscheck',
            name='moss_similarity_ratio',
            field=models.FloatField(default=0),
        ),
    ]
