# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_contestcodecrosscheck_moss_similarity_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
