# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wejudge.db.converter


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0014_contest_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestPrinterQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('is_finish', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.ContestAccount')),
                ('contest', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
            ],
            options={
                'verbose_name': '比赛打印代码功能表',
                'verbose_name_plural': '比赛打印代码功能表',
            },
            bases=(models.Model, wejudge.db.converter.ModelConverter),
        ),
    ]
