# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_contestprinterqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='enable_printer_queue',
            field=models.BooleanField(default=False),
        ),
    ]
