# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0017_contestaccount_passwd_retry_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsolution',
            name='best_code_size',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='contestsolution',
            name='best_memory',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='contestsolution',
            name='best_time',
            field=models.IntegerField(default=-1),
        ),
    ]
