# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0018_auto_20170728_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestaccount',
            name='archive_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestaccount',
            name='register_mode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
