# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0019_auto_20170824_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestaccount',
            name='archive_lock',
        ),
        migrations.RemoveField(
            model_name='contestaccount',
            name='register_mode',
        ),
        migrations.AddField(
            model_name='contest',
            name='archive_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='register_mode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
