# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0021_auto_20171005_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestproblem',
            name='status_editable',
        ),
        migrations.AddField(
            model_name='contestaccount',
            name='rank_last_ac_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='judger_mode',
            field=models.IntegerField(default=0),
        ),
    ]
