# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-07 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0022_auto_20171108_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='rank_list_show_items',
            field=models.IntegerField(default=0),
        ),
    ]
