# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_title', models.CharField(blank=True, max_length=255, null=True)),
                ('web_keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('web_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('web_version', models.CharField(blank=True, max_length=50, null=True)),
                ('web_fixing', models.BooleanField(default=False)),
                ('web_notice', models.TextField(default='')),
                ('web_stop_judging', models.BooleanField(default=False)),
                ('web_login_limit', models.BooleanField(default=False)),
                ('web_login_white_list', models.TextField(default='')),
                ('web_login_black_list', models.TextField(default='')),
                ('web_register', models.BooleanField(default=False)),
                ('smtp_server', models.CharField(blank=True, max_length=50, null=True)),
                ('smtp_user', models.CharField(blank=True, max_length=50, null=True)),
                ('smtp_pwd', models.CharField(blank=True, max_length=50, null=True)),
                ('smtp_mail_from', models.CharField(blank=True, max_length=50, null=True)),
                ('edu_year', models.SmallIntegerField(default=2016)),
                ('edu_term', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
