# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejudge', '0002_auto_20170403_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='edu_term',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='edu_year',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='web_login_black_list',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='web_login_limit',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='web_login_white_list',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='web_notice',
        ),
        migrations.AddField(
            model_name='setting',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
