# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.SmallIntegerField(choices=[(-1, '未知'), (0, '女'), (1, '男')], default=-1)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('realname', models.CharField(blank=True, max_length=50, null=True)),
                ('headimg', models.CharField(blank=True, max_length=50, null=True)),
                ('motto', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.IntegerField()),
                ('locked', models.BooleanField(default=False)),
                ('email_validated', models.BooleanField(default=False)),
                ('cookie_token', models.CharField(default='', max_length=100)),
                ('cookie_token_expire_at', models.IntegerField(default=0)),
                ('passwd_retry_counter', models.SmallIntegerField(default=10)),
                ('preference_language', models.CharField(default='gcc', max_length=10)),
                ('wc_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('wc_expires_in', models.CharField(blank=True, max_length=255, null=True)),
                ('wc_refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('wc_openid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('wc_user_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
