# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170115_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
