# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170115_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='permission_create_problemset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='permission_publish_problem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
