# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170119_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'WeJudge主账户表', 'verbose_name_plural': 'WeJudge主账户表'},
        ),
    ]
