# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_permission_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
