# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wejudge.db.converter


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20170419_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRemembermeTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default='', max_length=100)),
                ('user_agent', models.TextField(default='')),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
            ],
            bases=(models.Model, wejudge.db.converter.ModelConverter),
        ),
        migrations.RemoveField(
            model_name='account',
            name='cookie_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cookie_token_expire_at',
        ),
        migrations.AddField(
            model_name='accountremembermetokens',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
