# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20170518_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountremembermetokens',
            options={'verbose_name': '账户记住登录令牌表', 'verbose_name_plural': '账户记住登录令牌表'},
        ),
    ]
