# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20170607_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountremembermetokens',
            name='account',
        ),
        migrations.DeleteModel(
            name='AccountRemembermeTokens',
        ),
    ]
