# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('appname', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.CharField(blank=True, max_length=100, null=True)),
                ('app_id', models.CharField(max_length=100, unique=True)),
                ('app_secert', models.CharField(blank=True, max_length=100, null=True)),
                ('at_expires_time', models.IntegerField(default=7200)),
                ('rt_expires_time', models.IntegerField(default=604800)),
                ('redirect_uris', models.TextField(default='')),
                ('cancel_redirect_uri', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='OauthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('wejudge', 'WeJudge Master Account'), ('education', 'Education Account'), ('Contest', 'Contest Account')], default='wejudge', max_length=20)),
                ('account_id', models.IntegerField(default=0)),
                ('is_allow', models.BooleanField(default=False)),
                ('open_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('auth_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('auth_code_expires_at', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth2.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=100, unique=True)),
                ('refresh_token', models.CharField(max_length=100, unique=True)),
                ('expires_at', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='oauthuser',
            name='tokens',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='oauth2.Tokens'),
        ),
    ]
