# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthuser',
            name='tokens',
        ),
        migrations.AddField(
            model_name='oauthuser',
            name='tokens',
            field=models.ManyToManyField(blank=True, to='oauth2.Tokens'),
        ),
    ]
