# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0002_auto_20170927_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='app_secert',
            new_name='app_secret',
        ),
    ]
