# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='course_teacher', to='education.EduAccount'),
        ),
    ]
