# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20161214_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.ProblemClassify')),
            ],
        ),
        migrations.AddField(
            model_name='problemset',
            name='judge_status',
            field=models.ManyToManyField(blank=True, to='education.JudgeStatus'),
        ),
        migrations.AddField(
            model_name='problemset',
            name='permission',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problemclassify',
            name='problemset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.ProblemSet'),
        ),
        migrations.AddField(
            model_name='problemsetitem',
            name='classifications',
            field=models.ManyToManyField(blank=True, to='education.ProblemClassify'),
        ),
    ]
