# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20161226_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduaccount',
            name='last_login_time',
            field=models.DateTimeField(null=True),
        ),
    ]
