# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_eduaccount_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eduaccount',
            options={'verbose_name': '教学系统马甲账户', 'verbose_name_plural': '教学系统马甲账户'},
        ),
        migrations.AddField(
            model_name='eduschool',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='eduschool',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
