# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangement',
            name='password',
        ),
        migrations.AddField(
            model_name='arrangement',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
