# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_auto_20170313_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
