# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_auto_20170314_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemset',
            old_name='author',
            new_name='manager',
        ),
    ]
