# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-31 02:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_auto_20170328_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asgnaccesscontrol',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='asgnaccesscontrol',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
