# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_auto_20170403_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asgn',
            name='hide_problem_subcode',
        ),
        migrations.AlterField(
            model_name='asgnaccesscontrol',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asgnaccesscontrol',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
