# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wejudge.db.converter


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_auto_20170419_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduAccountProblemVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.IntegerField(default=0)),
                ('accepted', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '教学账户题目访问计数器缓存',
                'verbose_name_plural': '教学账户题目访问计数器缓存',
            },
            bases=(models.Model, wejudge.db.converter.ModelConverter),
        ),
        migrations.AddField(
            model_name='eduaccount',
            name='passwd_retry_counter',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='eduaccountproblemvisited',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.EduAccount'),
        ),
        migrations.AddField(
            model_name='eduaccountproblemvisited',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.AsgnProblem'),
        ),
    ]
