# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0022_auto_20170518_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduschool',
            name='short_name',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
    ]
