# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0023_eduschool_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='author',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='file_system',
        ),
        migrations.RemoveField(
            model_name='repositoryfs',
            name='parent',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='first_visit_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='ignore',
            new_name='penalty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='repositories',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='pe',
        ),
        migrations.AddField(
            model_name='asgnreport',
            name='excellent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asgnreport',
            name='public_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asgnreport',
            name='rank_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asgnreport',
            name='rank_timeused',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asgnreport',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='used_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='used_time_real',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
        migrations.DeleteModel(
            name='RepositoryFS',
        ),
    ]
