# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0024_auto_20170620_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='asgnproblem',
            name='hidden_answer',
            field=models.BooleanField(default=False),
        ),
    ]
