# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wejudge.db.converter


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0026_asgn_public_answer_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('handle', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('max_size', models.IntegerField(default=1073741824)),
                ('cur_size', models.IntegerField(default=0)),
                ('public_level', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.EduAccount')),
            ],
            options={
                'verbose_name': '教学资源仓库',
                'verbose_name_plural': '教学资源仓库',
            },
            bases=(models.Model, wejudge.db.converter.ModelConverter),
        ),
        migrations.CreateModel(
            name='RepositoryFS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dir', models.BooleanField(default=False)),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('entity', models.TextField(default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.RepositoryFS')),
            ],
            options={
                'verbose_name': '教学资源仓库文件系统表',
                'verbose_name_plural': '教学资源仓库文件系统表',
            },
            bases=(models.Model, wejudge.db.converter.ModelConverter),
        ),
        migrations.AddField(
            model_name='repository',
            name='file_system',
            field=models.ManyToManyField(blank=True, to='education.RepositoryFS'),
        ),
    ]
