# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0027_auto_20170703_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduschool',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eduschool',
            name='max_week',
            field=models.SmallIntegerField(default=17),
        ),
        migrations.AddField(
            model_name='eduschool',
            name='sections',
            field=models.TextField(default='{}'),
        ),
    ]
