# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0028_auto_20170704_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemclassify',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='problemclassify',
            name='problemset',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='items',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='judge_status',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='school',
        ),
        migrations.RemoveField(
            model_name='problemsetitem',
            name='classifications',
        ),
        migrations.RemoveField(
            model_name='problemsetitem',
            name='entity',
        ),
        migrations.DeleteModel(
            name='ProblemClassify',
        ),
        migrations.DeleteModel(
            name='ProblemSet',
        ),
        migrations.DeleteModel(
            name='ProblemSetItem',
        ),
    ]
