# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0029_auto_20170704_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.EduAccount'),
        ),
        migrations.AddField(
            model_name='course',
            name='repositories',
            field=models.ManyToManyField(blank=True, to='education.Repository'),
        ),
    ]
