# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0030_auto_20170708_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asgn',
            name='black_list',
        ),
        migrations.RemoveField(
            model_name='asgnvisitrequirement',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='asgnvisitrequirement',
            name='proc_time',
        ),
        migrations.RemoveField(
            model_name='asgnvisitrequirement',
            name='source_arrangement',
        ),
        migrations.AddField(
            model_name='asgn',
            name='hide_student_code',
            field=models.BooleanField(default=False),
        ),
    ]
