# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0031_auto_20170718_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='asgnproblem',
            name='asgn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_of_asgn', to='education.Asgn'),
        ),
        migrations.AlterField(
            model_name='asgn',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='asgn_items', to='education.AsgnProblem'),
        ),
    ]
