# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0032_auto_20170725_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduschool',
            name='theme_color',
            field=models.CharField(blank=True, default='#cccccc', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='best_code_size',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='solution',
            name='best_memory',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='solution',
            name='best_time',
            field=models.IntegerField(default=-1),
        ),
    ]
