# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0033_auto_20170728_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.EduSchool'),
        ),
        migrations.AddField(
            model_name='repositoryfs',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='children_nodes', to='education.RepositoryFS'),
        ),
        migrations.AlterField(
            model_name='repositoryfs',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_node', to='education.RepositoryFS'),
        ),
    ]
