# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0034_auto_20170807_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asgnproblem',
            old_name='pe_score',
            new_name='max_score_for_wrong',
        ),
        migrations.RemoveField(
            model_name='asgnproblem',
            name='ignore_pe',
        ),
        migrations.AddField(
            model_name='asgnproblem',
            name='strict_mode',
            field=models.BooleanField(default=False),
        ),
    ]
