# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0035_auto_20170807_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='file_system',
        ),
        migrations.AddField(
            model_name='repositoryfs',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Repository'),
        ),
    ]
