# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0036_auto_20170812_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositoryfs',
            name='children',
        ),
        migrations.RemoveField(
            model_name='repositoryfs',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='repositoryfs',
            name='repository',
        ),
        migrations.DeleteModel(
            name='RepositoryFS',
        ),
    ]
