# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0037_auto_20170812_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eduschool',
            name='theme_color',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='handle',
        ),
        migrations.AddField(
            model_name='eduschool',
            name='banner_style',
            field=models.CharField(blank=True, default='#cccccc', max_length=255, null=True),
        ),
    ]
