# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0040_asgnreport_attachment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asgnreport',
            unique_together=set([('author', 'asgn')]),
        ),
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together=set([('author', 'asgn', 'problem')]),
        ),
    ]
