# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wejudge.db.converter


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0041_auto_20171005_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduAccountRankList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.IntegerField(default=0)),
                ('accepted', models.IntegerField(default=0)),
                ('penalty', models.IntegerField(default=0)),
                ('solved', models.IntegerField(default=0)),
                ('ratio', models.FloatField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.EduAccount')),
            ],
            bases=(models.Model, wejudge.db.converter.ModelConverter),
        ),
        migrations.RemoveField(
            model_name='eduaccountproblemvisited',
            name='author',
        ),
        migrations.RemoveField(
            model_name='eduaccountproblemvisited',
            name='problem',
        ),
        migrations.DeleteModel(
            name='EduAccountProblemVisited',
        ),
    ]
